name: Test Poetry install

on:
  workflow_dispatch: # Put here!!
  push:
    branches:
      - rash598/bv1_dev
    paths:
      - '**/*.py'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: '3.10'  # Use your desired Python version
          
      - name: Change to project directory
        run: |
          cd byoeb-v1/byoeb-core
          ls
          
      - name: Poetry Install
        run: |
          pip install poetry
          cd byoeb-v1/byoeb-core
          poetry install --no-interaction
